<?php
// article.php - The Wrapper

// 1. SECURITY: Get the requested file ID
$requested_file = $_GET['id'] ?? '';

// Clean the input to prevent hacking (Directory Traversal)
// We only allow filenames that contain alphanumeric chars, underscores, dashes, and dots.
$clean_name = basename($requested_file);

// Define the path to the raw content
$file_path = __DIR__ . '/insights/' . $clean_name;

// 2. VALIDATION: Ensure file exists and is a valid article
$content = "";
$title = "Article Not Found";

if (!empty($clean_name) && file_exists($file_path) && str_ends_with($clean_name, '_article.html')) {
    // Load the raw HTML content generated by Python
    $content = file_get_contents($file_path);

    // Attempt to extract the <h2> to use as the Page Title
    if (preg_match('/<h2>(.*?)<\/h2>/', $content, $matches)) {
        $title = strip_tags($matches[1]);
    } else {
        $title = "DigitalABCs Insight";
    }
} else {
    // Handle 404
    header("HTTP/1.0 404 Not Found");
    $content = "<h2>Article Not Found</h2><p>The article you are looking for does not exist or has been moved.</p><a href='insights.php' class='btn-read-more'>Return to Insights</a>";
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4JD4ZCN0G8"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'G-4JD4ZCN0G8');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo htmlspecialchars($title); ?> - DigitalABCs</title>
    <meta name="description" content="Read the latest insights on AI, automation, and compliance from DigitalABCs.">

    <link rel="canonical" href="https://digitalabcs.com.au/article.php?id=<?php echo htmlspecialchars($clean_name); ?>">
    <link rel="icon" href="assets/favicon.ico" type="image/x-icon">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Roboto+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">

    <style>
        /* Article Specific Styling */
        .article-container {
            max_width: 800px;
            /* Constrain reading width for better UX */
            margin: 0 auto;
            padding: 60px 20px;
        }

        .article-content h2 {
            color: var(--color-navy, #1E3A8A);
            font-size: 2rem;
            margin-top: 0;
            margin-bottom: 1.5rem;
        }

        .article-content p {
            line-height: 1.8;
            font-size: 1.1rem;
            margin-bottom: 1.5rem;
            color: #333;
        }

        .article-content ul {
            margin-bottom: 1.5rem;
            padding-left: 20px;
        }

        .article-content li {
            margin-bottom: 10px;
            line-height: 1.6;
        }

        .article-content strong {
            color: var(--color-purple, #7C3AED);
        }

        .breadcrumb {
            margin-bottom: 20px;
            font-size: 0.9rem;
            color: #666;
        }

        .breadcrumb a {
            color: var(--color-purple, #7C3AED);
            text-decoration: none;
        }

        .article-image {
            width: 100%;
            height: auto;
            border-radius: 8px;
            margin-bottom: 30px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);
        }
    </style>
</head>

<body>
    <a href="#main-content" class="skip-link">Skip to main content</a>
    <header class="site-header">
        <div class="container">
            <a href="index.html" class="logo" aria-label="DigitalABCs Home">
                <img src="assets/logo.png" alt="DigitalABCs Logo" class="logo-img">
            </a>
            <nav class="main-nav">
                <ul>
                    <li><a href="index.html">Home</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="services.html">Services</a></li>
                    <li><a href="insights.php" class="active">Insights</a></li>
                    <li><a href="contact.html">Contact</a></li>
                    <a href="https://services.digitalabcs.com.au" target="_blank">Client Login</a>
                </ul>
            </nav>
        </div>
        <script async src="https://tally.so/widgets/embed.js"></script>
    </header>

    <main id="main-content">
        <article class="article-container">
            <div class="breadcrumb">
                <a href="insights.php">&larr; Back to Insights</a>
            </div>

            <?php
            $thumb_name = str_replace('_article.html', '_thumbnail.png', $clean_name);
            $thumb_path = __DIR__ . '/insights/' . $thumb_name;
            if (file_exists($thumb_path)) {
                echo '<img src="insights/' . htmlspecialchars($thumb_name) . '" class="article-image" alt="Article Illustration">';
            }
            ?>

            <div class="article-content">
                <?php echo $content; ?>
            </div>

            <div class="section-divider"></div>
            <div style="background: #f0f9ff; padding: 20px; border-radius: 8px; margin-top: 30px;">
                <h3 style="margin-top:0; color: var(--color-navy);">Need help implementing this?</h3>
                <p style="margin-bottom: 15px;">Stop being the rescuer in your own business. Let's build a system that handles this for you.</p>
                <a href="contact.html" class="btn-read-more">Book a Digital Systems Audit</a>
            </div>
        </article>
    </main>

    <footer class="site-footer">
        <div class="container">
            <div class="footer-grid">
                <div class="footer-col">
                    <h4>DigitalABCs</h4>
                    <p>Empowering Australian businesses through practical technology. Built on resilience, for resilience.</p>
                </div>
                <div class="footer-col">
                    <h4>Navigate</h4>
                    <ul>
                        <li><a href="about.html">About Us</a></li>
                        <li><a href="services.html">Our Services</a></li>
                        <li><a href="insights.php">Insights</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Legal</h4>
                    <ul>
                        <li><a href="privacy.html">Privacy Policy</a></li>
                        <li><a href="terms.html">Terms of Service</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Connect</h4>
                    <p>info@digitalabcs.com.au<br>Toongabbie, NSW, Australia</p>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; 2025 DigitalABCs. All rights reserved.</p>
            </div>
        </div>
    </footer>

    <style>
        .tally-float-btn {
            position: fixed;
            bottom: 20px;
            right: 20px;
            background-color: #ba38eb;
            color: #fff;
            border: none;
            border-radius: 50px;
            padding: 14px 22px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            z-index: 9999;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            display: flex;
            align-items: center;
            gap: 8px;
            transition: all 0.2s ease-in-out;
        }

        .tally-float-btn:hover {
            background-color: #10B981;
            transform: translateY(-2px);
        }

        @media (max-width: 600px) {
            .tally-float-btn {
                padding: 12px 18px;
                font-size: 14px;
                bottom: 15px;
                right: 15px;
            }
        }
    </style>
    <button class="tally-float-btn" data-tally-open="wkDaP1" data-tally-layout="modal" data-tally-width="700" data-tally-overlay="true" data-tally-hide-title="false" data-tally-emoji-text="ðŸ’¡" data-tally-emoji-animation="tada"> Where are you in your AI journey?</button>
</body>

</html>